// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhoaHoc.Data;

#nullable disable

namespace QuanLyKhoaHoc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530024532_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKhoaHoc.Models.GiangVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SoNamKinhNghiem")
                        .HasColumnType("int");

                    b.Property<string>("strChuyenMon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("strEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("strHoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("strSoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("GiangViens");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.KhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GiangVienId")
                        .HasColumnType("int");

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SoBuoiHoc")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<DateTime>("dtNgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtNgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("strMoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strTenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.ToTable("KhoaHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.KhoaHoc", b =>
                {
                    b.HasOne("QuanLyKhoaHoc.Models.GiangVien", "GiangVien")
                        .WithMany("lstKhoaHocs")
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("QuanLyKhoaHoc.Models.GiangVien", b =>
                {
                    b.Navigation("lstKhoaHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
